### ISSUE TITLE
New tool: LinkSheet

### ISSUE THREAD

**Issue by PhilC813** [duyfken/alternative-front-ends#4]
### What platform does this front-end run on?

Mobile (Android/iOS)

### Front-end Name

LinkSheet

### Front-end For

Many;
The full list is likely within its source code or the one of the [LibRedirect implementation](https://github.com/1fexd/libredirectkt) that it uses.

### Front-end Repository

https://github.com/LinkSheet/LinkSheet

### Main/Official Instance

N/A

**Comment by PhilC813** [comment]
While it isn't the main feature of the app, it provides the same capability as [UntrackMe](https://framagit.org/tom79/nitterizeme), which is currently one of the two entries in the "[Tools](https://github.com/duyfken/alternative-front-ends/tree/mobile?tab=readme-ov-file#tools)" section of the list. However, unlike UntrackMe, it is still actively maintained, and is significantly much versatile by allowing redirects to multiple alternative front-ends using an implementation of [LibRedirect](https://github.com/libredirect/libredirect).

**Comment by duyfken** [comment]
Added with https://github.com/duyfken/alternative-front-ends/commit/3ba7a509ab42895d8158d71c64281b8013aceb2b
