### ISSUE TITLE
New tool: LibRedirect browser extension (Firefox for Android)

### ISSUE THREAD

**Issue by PhilC813** [duyfken/alternative-front-ends#5]
### What platform does this front-end run on?

Mobile (Android/iOS)

### Front-end Name

LibRedirect

### Front-end For

Many;
See their [website](https://libredirect.github.io) for the full list

### Front-end Repository

https://github.com/libredirect/browser_extension

### Main/Official Instance

https://addons.mozilla.org/android/addon/libredirect

**Comment by duyfken** [comment]
Added with https://github.com/duyfken/alternative-front-ends/commit/0025ef3af3c948e834cd65745e44501ccf058669
